/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void test(uint8_t a,uint8_t b)
{
	uint16_t res=a+b;
}
int main(void)
{
#if 0
	uint32_t SVC_Final;
	printf("Ready\n");

	__asm volatile ("SVC #22");
//	register uint32_t data __asm("r0");
	__asm volatile("MOV %0,R0":"=r"(SVC_Final));
	printf("SVC Number after coming from SVC handler: %lu\n",SVC_Final);
#endif

	uint8_t val1=20,val2=12;
	test(val1,val2);
	uint16_t res;
	__asm volatile("MOV R0,%0"::"r"(val1));
	__asm volatile("MOV R1,%0"::"r"(val2));
	__asm volatile("SVC #39");
	__asm volatile("MOV %0,R0":"=r"(res));
	printf("Result= %u\n",res);
	/* Loop forever */
	for(;;);
}

__attribute__((naked)) void SVC_Handler()
{
	__asm volatile("MRS R0,MSP");
	__asm volatile("B SVC_math");
}
#if 0
void SVC_new(uint32_t *pMSP)
{
	uint8_t *PC_t=(uint8_t *)*(pMSP+6);
	PC_t-=2;
	uint8_t SVCNo=*PC_t;
	printf("SVC Number: %u\n",SVCNo);
	SVCNo+=4;
	pMSP[0]=SVCNo;

}
#endif

void SVC_math(uint32_t *pbaseAddr)
{
	uint8_t *pData=(uint8_t *)pbaseAddr[6];
	pData-=2;
	uint8_t SVCNo=*pData;
	switch(SVCNo)
	{
	case 36:
		pbaseAddr[0]+=pbaseAddr[1];
		break;
	case 37:
		pbaseAddr[0]-=pbaseAddr[1];
		break;
	case 38:
		pbaseAddr[0]*=pbaseAddr[1];
		break;
	case 39:
		pbaseAddr[0]/=pbaseAddr[1];
		break;

	}

}
